const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=['query','university','technology','category','year','status'];
const options={university:UNIVERSITIES,technology:[...new Set(RECORDS.flatMap(r=>r.tech))],category:[...new Set([...RECORDS.map(r=>r.category),'논문','특허','석박사 배출','기술이전'])]};
Object.entries(options).forEach(([k,a])=>a.forEach(v=>$('#'+k).add(new Option(v,v))));
const params=new URLSearchParams(location.search);fields.forEach(k=>{if(params.has(k))$('#'+k).value=params.get(k)});
let shown=[],zoom=1,pan={x:0,y:0},selected=null;
function sourceLinks(ids){return ids.map(id=>{let s=SOURCES.find(s=>s.id===id);return `<a target="_blank" rel="noopener" href="${esc(s.url)}">[${id}] ${esc(s.title)} ↗</a>`}).join('<br>')}
function filtered(){let f=Object.fromEntries(fields.map(k=>[k,$('#'+k).value]));return RECORDS.filter(r=>(!f.query||JSON.stringify(r).toLowerCase().includes(f.query.toLowerCase()))&&(!f.university||r.universities.includes(f.university))&&(!f.technology||r.tech.includes(f.technology))&&(!f.category||r.category===f.category)&&(!f.status||r.status===f.status)&&(f.year==='all'||(f.year?r.year===+f.year:r.year>=2021&&r.year<=2025)));}
function choose(id){let r=RECORDS.find(r=>r.id===id);if(!r)return;selected=id;$('#detail').innerHTML=`<p class="eyebrow">${r.id} / ${r.year||'시점 미상'}</p><span class="badge ${r.status==='계획·모집'?'plan':''}">${r.status}</span><h2>${esc(r.title)}</h2><p>${r.universities.join(' · ')}</p><p>${esc(r.summary)}</p><div class="note"><b>해석의 경계</b><p>${esc(r.limit)}</p></div><p class="small">태그: ${r.tech.join(' · ')}<br>확인일 ${r.verified}</p>${sourceLinks(r.source)}`;draw();}
function update(){shown=filtered();$('#count').textContent=`${shown.length}개 근거 기록`;$('#results').innerHTML=shown.length?shown.map(r=>`<article class="card"><span class="badge ${r.status==='계획·모집'?'plan':''}">${r.status}</span><span class="meta">${r.year||'시점 미상'} · ${r.id}</span><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><div class="meta">${r.universities.join(' · ')} / ${r.tech.join(' · ')}</div><button data-record="${r.id}">근거와 한계 읽기 ↗</button></article>`).join(''):'<div class="empty"><h3>이 조건에 맞는 검증 기록이 없습니다.</h3><p>성과가 0건이라는 뜻은 아닙니다. 논문·특허·학위·기술이전은 사업 귀속을 확인할 원자료가 필요합니다. 조건을 넓히거나 아래 근거와 방법을 확인하세요.</p></div>';document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>{choose(b.dataset.record);$('#detail').scrollIntoView({behavior:'smooth',block:'nearest'})});if(selected&&!shown.some(r=>r.id===selected)){$('#detail').innerHTML='<p class="eyebrow">FILTER UPDATED</p><h2>새로운 연결을 살펴보세요.</h2><p>기록을 선택하면 원문과 집계 한계가 표시됩니다.</p>';selected=null}draw();const p=new URLSearchParams();fields.forEach(k=>{if($('#'+k).value)p.set(k,$('#'+k).value)});history.replaceState(null,'',location.pathname+(p.size?'?'+p:'')+location.hash);}
function draw(){let us=UNIVERSITIES.filter(u=>shown.some(r=>r.universities.includes(u))),ts=[...new Set(shown.flatMap(r=>r.tech))];let nodes=[...us.map((v,i)=>({id:'u'+v,label:v,type:'u',x:90,y:45+i*380/Math.max(us.length-1,1)})),...ts.map((v,i)=>({id:'t'+v,label:v,type:'t',x:600,y:35+i*400/Math.max(ts.length-1,1)})),...shown.map((r,i)=>({id:r.id,label:r.id,type:'r',x:285+(i%2)*115,y:30+Math.floor(i/2)*410/Math.max(Math.ceil(shown.length/2)-1,1)}))];let by=Object.fromEntries(nodes.map(n=>[n.id,n])),lines='';shown.forEach(r=>[...r.universities.map(u=>'u'+u),...r.tech.map(t=>'t'+t)].forEach(id=>{let a=by[r.id],b=by[id];if(b)lines+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${selected===r.id?'#6ce0cd':'#344b61'}" stroke-opacity="${selected&&selected!==r.id?.25:.7}"/>`}));$('#map').innerHTML=`<svg viewBox="0 0 700 475" role="group" aria-label="대학과 기술을 연결하는 공개기록"><g id="scene" transform="translate(${pan.x} ${pan.y}) scale(${zoom})">${lines}${nodes.map(n=>`<g class="node" tabindex="0" role="button" aria-label="${esc(n.type==='r'?RECORDS.find(r=>r.id===n.id).title:n.label+' 필터')}" data-id="${esc(n.id)}"><circle cx="${n.x}" cy="${n.y}" r="${n.type==='r'?11:20}" fill="${n.type==='u'?'#6ce0cd':n.type==='t'?'#b6a2ff':selected===n.id?'#6ce0cd':'#20364d'}" stroke="${n.type==='r'?'#90adca':'none'}"/><text text-anchor="middle" x="${n.x}" y="${n.y+(n.type==='r'?26:37)}">${esc(n.label)}</text></g>`).join('')}</g></svg>`;$('#map').querySelectorAll('.node').forEach(n=>{const run=()=>{let id=n.dataset.id;if(id[0]==='R')choose(id);else{$(id[0]==='u'?'#university':'#technology').value=id.slice(1);update()}};n.onclick=run;n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run()}}});}
fields.forEach(k=>$('#'+k).addEventListener(k==='query'?'input':'change',update));$('#reset').onclick=()=>{fields.forEach(k=>$('#'+k).value='');selected=null;zoom=1;pan={x:0,y:0};update()};$('#zoomin').onclick=()=>{zoom=Math.min(2.5,zoom+.2);draw()};$('#zoomout').onclick=()=>{zoom=Math.max(.5,zoom-.2);draw()};$('#fit').onclick=()=>{zoom=1;pan={x:0,y:0};draw()};let drag;$('#map').onpointerdown=e=>{if(e.target.closest('.node'))return;drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};$('#map').setPointerCapture(e.pointerId)};$('#map').onpointermove=e=>{if(!drag)return;let scale=700/$('#map').clientWidth;pan={x:drag.px+(e.clientX-drag.x)*scale,y:drag.py+(e.clientY-drag.y)*scale};let g=$('#scene');if(g)g.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${zoom})`)};$('#map').onpointerup=()=>drag=null;$('#map').onpointercancel=()=>drag=null;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('현재 검색 조건이 담긴 링크를 복사했습니다.')}catch{toast('주소창의 URL을 복사하면 검색 조건이 유지됩니다.')}};
$('#export').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';let csv=[['ID','제목','연도','대학','기술','유형','근거구분','확인내용','한계','출처URL','확인일'],...shown.map(r=>[r.id,r.title,r.year,r.universities.join('|'),r.tech.join('|'),r.category,r.status,r.summary,r.limit,r.source.map(id=>SOURCES.find(s=>s.id===id).url).join('|'),r.verified])].map(row=>row.map(cell).join(',')).join('\r\n');let url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='xr-evidence.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const profiles=[
['건국대','주관·공유 운영','2022 맵 제작 모집, 2023 노코드 게임 과정. 컨소시엄 운영 구조의 근거가 있으나 대학 자체 5개년 확정 성과와는 구분.','공동 자산의 버전·라이선스·외부 재사용 관리 허브','S03'],
['경희대','기술 교육·사업화 연결','2025 경희·배재 연합팀 수상 및 콘텐츠진흥원 사업 선정. 관련 햅틱·생성 AI 과제는 사업 귀속 미확인.','휴먼 인터랙션 평가와 기업 수요를 연결하는 실증','S09'],
['계명대','교과 제작·성과 전시','2025 EXPO의 영상·XR 교과 참여 결과 확인. 학과 게시물의 범위를 대학 전체로 확장하지 않음.','제작 포트폴리오와 외부 평가·취업 추적의 연결','S11'],
['계원예대','캐릭터·VR·전시 디자인','2024 영상 아카이브에서 제작 교육 확인. 현재 MD 안내를 과거 연도 실적으로 소급하지 않음.','디지털 휴먼의 서사·공간 경험·AI 제작 품질 검증','S06'],
['배재대','PBL·교육 콘텐츠','2023 과정 목록 및 2025 게임·VR 수상 확인. 교육 콘텐츠의 실제 효과와 이용 지속성은 추가 검증 필요.','교육·지역 수요에서 사용성·학습 전이 검증','S10'],
['전주대','사회문제·지산학','2024 쇼케이스에서 교양 프로젝트와 지역·산업·투자 주체 참여 확인. 아이디어 발굴과 상용화 구분.','지역 현장 문제의 장기 실증과 접근성 연구','S08'],
['중앙대','콘텐츠·비즈니스·국제 교류','2025 교과과정, 국제 컨퍼런스, 산관학 워크숍 확인. 창업 행사 참여와 기업 설립은 별도 지표.','콘텐츠 IP·AI 제작·글로벌 시장 검증의 결합','S12']];
$('#comparison').innerHTML=`<div class="coverage">공개사례 기반 해석이며 대학별 공식 특성화 지정이나 순위가 아닙니다. 논문·특허·석박사·기술이전의 연도별 확정 총계는 모두 미확인입니다.</div><div class="table-wrap"><table><thead><tr><th>대학</th><th>관찰된 축</th><th>확인된 공개사례 / 한계</th><th>후속 역할 제안</th></tr></thead><tbody>${profiles.map(p=>`<tr><td>${p[0]}<br><button class="link-button" data-uni="${p[0]}">기록 탐색</button></td><td>${p[1]}</td><td>${p[2]}<br>${sourceLinks([p[4]])}</td><td>${p[3]}<br><span class="badge plan">분석 제안</span></td></tr>`).join('')}</tbody></table></div><details><summary>5개년 공개기록 분포 보기 · 실적 총계 아님</summary><p class="small">이 초판에 수록한 기록의 연도 분포입니다. 관련 연구·언론 보도·모집 포함. 공동 기록은 여러 대학에 표시하므로 열을 합산하지 않습니다.</p><div class="table-wrap"><table><thead><tr><th>대학</th>${[2021,2022,2023,2024,2025].map(y=>`<th>${y}</th>`).join('')}</tr></thead><tbody>${UNIVERSITIES.map(u=>`<tr><td>${u}</td>${[2021,2022,2023,2024,2025].map(y=>{let rs=RECORDS.filter(r=>r.year===y&&r.universities.includes(u));return `<td>${rs.length?rs.map(r=>`<button data-jump="${r.id}">${r.id}</button>`).join(' '):'수록 근거 없음'}</td>`}).join('')}</tr>`).join('')}</tbody></table></div></details>`;
document.querySelectorAll('[data-uni]').forEach(b=>b.onclick=()=>{fields.forEach(k=>$('#'+k).value='');$('#university').value=b.dataset.uni;update();$('#explore').scrollIntoView()});document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{fields.forEach(k=>$('#'+k).value='');update();choose(b.dataset.jump);$('#explore').scrollIntoView()});
const eras=[['2021','공유교육의 출발','공유대학 체계와 신기술 인재양성 목표 설정. 교육 접근성·교과 공유가 평가의 출발점.','S01'],['2022','메타버스 제작 진입','랜드마크 맵과 메타버스 과정 모집. 콘텐츠 저작의 진입 경로를 관찰할 수 있음.','S03'],['2023','참여·PBL 확장','노코드 제작 및 PBL 발표·전시 과정 등장. 운영 안내와 실제 성과는 분리해서 평가.','S05'],['2024','경험·사회문제 연결','VR 제작·전시와 지역 쇼케이스. AI 스마트글라스 아이디어 등 휴먼 중심 적용 사례.','S08'],['2025','교과·산업·국제 접점','제작 EXPO, 교육용 VR 수상, 사업화 지원 연계. 효과·고용·매출 추적은 여전히 과제.','S10'],['2026+','AI·XR 통합의 질문','AI 제작 인터뷰와 메타휴먼 연구를 후속 방향의 신호로 활용. 과거 5개년 실적과 분리.','S23']];
$('#timeline').innerHTML=eras.map(e=>`<article class="era"><strong>${e[0]}</strong><h3>${e[1]}</h3><p>${e[2]}</p>${sourceLinks([e[3]])}</article>`).join('');
const strategies=[
['01','휴먼 중심 실증을 공통 평가축으로','교육·문화·접근성 등 실제 문제를 먼저 정하고 XR의 추가 가치를 비교한다. 학생·현장 사용자와 공동 설계한 과제로 연결한다.','학습 전이·과업 성공률·불편감·재방문율을 비교군과 함께 측정. 이용자 특성별 격차도 보고.','전주대 아이디어, 배재대 교육용 VR 사례의 다음 단계','S08','S10'],
['02','AI 제작을 재현 가능한 연구로','프롬프트 사용 교육을 넘어 데이터 출처, 제작 과정, 모델·도구 버전, 편집 이력을 남긴다. 디지털 휴먼의 일관성과 제어 가능성을 연구한다.','동일 품질에서 제작 시간·비용, 장면 일관성, 편집 가능성, 사용자 평가를 함께 비교.','AI 제작 교육과 메타휴먼 서사 연구의 접점','S02','S23'],
['03','공유 플랫폼을 상호운용성으로 평가','OpenXR의 런타임·디바이스 연결과 OpenUSD의 장면·자산 교환을 구분해 교육용 시험 환경을 만든다. 단일 캠퍼스 구축보다 자산 재사용을 우선한다.','다른 도구·기기에서 재현되는 과제 비율, 이전 비용, 외부 수업 재사용 수. 표준이 경제·신원 호환까지 보장한다고 주장하지 않음.','표준 기반 교육·실증 방향 제안','S20','S21'],
['04','산학 협력을 문제 정의부터 공동 수행','기업·지자체의 과제를 공개하고 학생 제작물에서 현장 실증까지 단계별 계약·역할을 분리한다. 연구기관은 평가 설계와 재현 검증을 담당하도록 제안한다.','행사·협약 수 대신 실증 완료, 반복 구매·사용, 유료 전환, 현장 채택 및 기여도 확인.','교류·쇼케이스를 지속적 활용으로 연결','S08','S13'],
['05','학부–대학원–창업의 이동 경로 추적','교육사업의 중심인 학부 이수와 대학원 연구를 분리하되, 동의를 받은 추적 코호트로 진학·고용·창업 경로를 연결한다. 계원예대의 학제 차이를 고려한다.','고유 이수자, 진학·전공 관련 취업, 12·24개월 창업 생존. 응답률과 추적 탈락률을 함께 공개.','교육 편성과 사업화 지원을 넘어선 결과 평가','S14','S09'],
['06','성과 원장을 사업의 공통 인프라로','대학마다 같은 데이터 사전과 영구 식별자를 사용한다. 논문 DOI·특허번호·계약번호·교과·프로젝트 ID로 중복과 사업 귀속을 관리한다.','증빙 연결률, 외부 재현·재사용, 정정 소요시간. 성과 미공개·미확인·해당 없음을 구분.','공개 자료의 공백에 대한 분석자의 개선 제안','S01','S18']];
$('#recommendations').innerHTML=`<div class="thesis"><p class="eyebrow" style="color:#6ce0cd">독립 분석 · 정책 제안</p><h3>교육 기반은 확인된다.<br>다음 과제는 ‘지속되는 사용’의 입증이다.</h3><p>공동교육과 제작·교류 사례는 확인되지만, 그 자체로 산업 경쟁력 향상이나 사업의 인과적 효과가 입증되지는 않습니다. 후속사업은 교육 접근성이라는 본래 목적을 유지하면서, 학습·현장 활용·고용으로 이어지는 과정을 추적해야 합니다.</p><p>AI는 제작 진입 장벽을 낮출 가능성이 있지만 검증·편집·권리 관리의 과제도 만듭니다. 3D Gaussian Splatting 같은 공간 표현 연구는 새로운 제작 경로의 근거이며, 컨소시엄의 자체 연구 실적은 아닙니다. ${sourceLinks(['S19'])}</p></div><div class="grid3">${strategies.map(s=>`<article class="strategy"><span class="number">PRIORITY ${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p><p><b>어떻게 평가할까</b><br>${s[3]}</p><p class="small">${s[4]}</p>${sourceLinks(s.slice(5))}</article>`).join('')}</div><h3 style="margin-top:35px">진정한 메타버스 플랫폼의 도래가 재개되나?</h3><p><b>가능성은 열려 있지만, 공개 근거만으로 ‘재도래’를 확정할 수 없습니다.</b> 여기서는 메타버스를 여러 사람이 지속적으로 이용하고, 공간·자산·상호작용이 연결되는 경험으로 정의합니다. AI 콘텐츠 생성이나 XR 기기 보급만으로 이 조건이 완성되지는 않습니다.</p><div class="grid3"><article class="card"><span class="badge">조건부 시나리오 A</span><h3>분야별 실용 플랫폼</h3><p>교육·문화·설계 등 특정 문제에서 AI와 XR이 통합됩니다. 가장 먼저 검증할 실증 가설이며 확률 예측은 아닙니다.</p><b>관찰 지표</b><p>반복 이용, 과업 성과, 운영 비용, 현장 채택</p></article><article class="card"><span class="badge">조건부 시나리오 B</span><h3>연결된 개방 생태계</h3><p>표준을 통한 공간 자산 재사용과 디바이스 호환이 확대됩니다. 신원·권리·결제·실시간 동기화는 별도 해결이 필요합니다.</p><b>관찰 지표</b><p>도구 간 자산 교환 성공률, 이식 비용, 호환성 시험</p></article><article class="card"><span class="badge plan">조건부 시나리오 C</span><h3>분절된 체험의 지속</h3><p>기기 부담·콘텐츠 운영비·낮은 재방문으로 체험이 일회성에 머뭅니다. 단일 플랫폼 투자 확대를 재검토해야 하는 신호입니다.</p><b>관찰 지표</b><p>낮은 재사용, 높은 유지비, 사업 종료 후 서비스 중단</p></article></div><p class="small">분석자의 시나리오입니다. 시장규모·발생확률·사업 성공을 수치로 예측하지 않습니다. 표준 근거: ${sourceLinks(['S20','S21'])}</p><h3>후속사업 실행 순서 · 착수 후 상대 일정 제안</h3><div class="table-wrap"><table><thead><tr><th>단계</th><th>우선 과제</th><th>진행 판단 기준</th></tr></thead><tbody><tr><td>0–6개월</td><td>7개교 성과 원장 정비, 중복 해소, 기초 사용자·교육 현황 측정</td><td>귀속·연도·증빙이 검증된 기준선 확보</td></tr><tr><td>6–18개월</td><td>교육·문화·접근성 분야 공동 실증, AI 제작·공간 호환 비교 실험</td><td>비교군 대비 유용성과 재현성, 적정 운영비</td></tr><tr><td>18–36개월</td><td>검증된 과제의 외부 대학·기업 이전 및 추적</td><td>외부 재사용·현장 채택·지속 운영이 확인된 경우 확대</td></tr></tbody></table></div><h3>학생·연구자를 위한 진입 경로</h3><div class="grid3"><article class="card"><h3>기술을 만들고 싶다면</h3><p>프로그래밍·수학·3D 그래픽스 → XR 인터랙션 → 사용자 평가. 경희대 기술 MD와 관련 연구를 함께 살펴보되 지원 조건은 해당 대학 공지를 확인하세요.</p>${sourceLinks(['S15','S16'])}</article><article class="card"><h3>경험을 디자인하고 싶다면</h3><p>스토리·공간·영상 기초 → VR 제작·모션캡처 → 관객 경험 평가. 계원예대의 시네마틱 VR·캐릭터 교육을 탐색할 수 있습니다.</p>${sourceLinks(['S22','S07'])}</article><article class="card"><h3>연구·사업화로 이어가려면</h3><p>현장 문제 정의 → 작은 프로토타입 → 사용자 검증 → 논문·IP·사업모델 검토. 중앙대 교육과 경희대 사업화 사례는 경로 참고자료이며 현재 모집 공고가 아닙니다.</p>${sourceLinks(['S14','S09'])}</article></div>`;
$('#method').innerHTML=`<div class="grid2"><article class="card"><h3>무엇을 조사했나</h3><p>교육부, 사업단 홈페이지·LMS, 7개교의 공개 교육·뉴스·연구 안내, KCI 및 기술 원문을 검색했습니다. 2021–2025 역년을 기본 분석 기간으로 사용하고 2026 및 시점 미상 자료를 분리했습니다. 회계·학년도 성과는 원장 확보 후 재집계해야 합니다.</p><p>이 초판은 공개 사례를 구조화한 탐색형 분석입니다. 전수조사나 공식 성과평가 보고서가 아니며, 학교별 연차보고서·논문 사사·특허 원장·학위 원장을 아직 확보하지 못했습니다.</p></article><article class="card"><h3>근거와 해석을 분리</h3><p><b>공식 발표:</b> 기관이 발표한 사실·수치. 외부 감사 완료를 뜻하지 않음.<br><b>계획·모집:</b> 프로그램 안내. 완료 실적에 합산하지 않음.<br><b>관련 연구:</b> 대학·저자 연관은 확인, 사업 지원은 미확인.<br><b>언론 보도:</b> 원장과 독립 대조가 필요한 보조 근거.</p><p>기술 태그와 대학별 관찰 축은 원문을 바탕으로 한 분석자 분류입니다. 관계선은 태그 연결이며 협력의 강도나 인과관계를 표현하지 않습니다.</p></article></div><h3>요청 지표의 공개 확인 상태와 추가 증빙</h3><div class="table-wrap"><table><thead><tr><th>지표</th><th>현재 상태</th><th>확정에 필요한 증빙 · 집계 원칙</th></tr></thead><tbody><tr><td>논문</td><td>5개년 사업 귀속 총계 미확인</td><td>DOI/KCI ID, 출판연도, 저자 소속, 사사·과제번호. 공저 논문은 컨소시엄 1건, 대학 기여 별도. 2026 관련 논문 R23은 제외.</td></tr><tr><td>특허</td><td>미확인</td><td>출원·등록번호, 권리자, 발명자, 사업 과제번호, 법적 상태. 출원과 등록, 국가별 동족을 구분.</td></tr><tr><td>석박사 배출</td><td>미확인</td><td>학위수여 원장과 참여 코호트 연결. 입학·수료·졸업을 구분하고 학부 MD를 학위로 세지 않음. 학제에 따라 해당 여부를 먼저 판단.</td></tr><tr><td>기술이전</td><td>미확인</td><td>계약 원장, 대상 기술, 귀속 과제, 계약·실수입 금액, 실증 또는 도입 확인. MOU와 계약을 구분.</td></tr><tr><td>창업</td><td>지원·행사 사례 및 누적 보도 존재</td><td>기업 식별자, 설립일, 참여 이력, 고용·매출·생존. 모집 목표·팀·법인 수를 분리. R17의 42건 이상은 독립 검증 전.</td></tr><tr><td>관련 사업·산학관연</td><td>선정·교류 사례 확인</td><td>협약·과제번호·재원·수행기관·참여 역할·결과물. 단순 참여·후원과 공동 연구개발을 구분.</td></tr><tr><td>교육·콘텐츠·공유</td><td>교과·프로젝트·수상 사례 확인</td><td>고유 이수자, 교과 완수율, 학습효과, 타교 재사용, 외부 이용, 저장소·콘텐츠 라이선스.</td></tr></tbody></table></div><div class="note"><b>빠진 지표도 함께 평가해야 합니다.</b><p>비전공자·지역별 접근성, 대학 간 학점교류의 실제 이용, 학습 전이, 전공 관련 고용, 장비 활용·유지비, 사업 종료 후 운영 가능성, 콘텐츠 권리와 접근성, 외부 재사용, 원장 공개 품질을 추가합니다. 이 지표들은 후속 평가 제안이며 현재 실측 결과가 아닙니다.</p></div><p>자료 정정은 원문·날짜·변경 이유를 함께 기록하는 방식으로 관리하도록 설계했습니다. 현재 버전은 고정된 검토 자료이며 자동 갱신되지 않습니다. 대학별 비공개 원장 없이 확정 성과 순위·ROI·사업의 인과적 효과를 산출하지 않습니다.</p>`;
$('#bibliography').innerHTML=SOURCES.map(s=>`<p><b>${s.id}</b> · <a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><br><span class="small">원문 시점: ${s.date} · 확인일: ${s.accessed}</span></p>`).join('');
update();if(shown.some(r=>r.id==='R07'))choose('R07');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'filter_xr_evidence',title:'XR 공개근거 필터',description:'웹의 검색 조건을 변경하고 확인 가능한 공개기록을 반환합니다. 사업 확정 총계를 산출하지 않습니다.',inputSchema:{type:'object',properties:{query:{type:'string'},university:{type:'string',enum:['',...UNIVERSITIES]},year:{type:'string',enum:['','2021','2022','2023','2024','2025','2026','all']}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['query','university','year'].includes(k)))throw Error('유효하지 않은 필터');for(let [k,v]of Object.entries(input)){if(typeof v!=='string'||(k==='university'&&!['',...UNIVERSITIES].includes(v))||(k==='year'&&!['','2021','2022','2023','2024','2025','2026','all'].includes(v)))throw Error('지원하지 않는 필터 값')}fields.forEach(k=>$('#'+k).value='');Object.entries(input).forEach(([k,v])=>$('#'+k).value=v);update();return{count:shown.length,records:shown.map(r=>({id:r.id,title:r.title,status:r.status}))}}})).catch(()=>{})}catch{}}
