const fundSection=document.createElement('section');fundSection.id='funding';
fundSection.innerHTML=`<div class="fund-hero"><p class="eyebrow">2027 R&D · CROSS-MINISTRY CONNECTIONS</p><h1>배움에서 연구로,<br><span>연구에서 문화산업의 현장으로.</span></h1><p>휴먼–AI–XR 실감융합 공유캠퍼스를 교육·연구개발·실증·사업화로 연결하는 후속사업 제안</p><span class="budget-status">2026.09.29 기준 · 2027년 정부 예산안 · 국회 확정 전</span></div>
<div class="budget-kpis"><article><small>국가 R&D 전체</small><strong>39.5<em>조원</em></strong><p>2026년 35.5조원 → 2027년 안<br>정부자료 증가율 +11.2%</p></article><article><small>문체부 CT 생태계</small><strong>2,406<em>억원</em></strong><p>R&D + 보조사업 + 정부 펀드 출자<br>전년 본예산 대비 +13.7%</p></article><article><small>그중 문체부 CT R&D</small><strong>1,774<em>억원</em></strong><p>2026년 약 1,515억원 → 2027년 안<br>전년 본예산 대비 +17.1%</p></article></div>
<p class="small">상단 문체부 수치는 억원 단위 반올림. 정밀값·범위는 아래 표에 표시했습니다. 전국 예산이며 우리 컨소시엄의 확보액이 아닙니다. ${sourceLinks(['S29','S30'])}</p>
<div class="budget-layout"><div><h2>2,406억원은 어떻게 구성되나?</h2><div class="budget-stack" aria-label="2027 CT 생태계 정부안 구성: R&D 1774.14억원, 보조사업 32억원, 펀드 출자 600억원"><span style="flex:1774.14;background:#167b83"></span><span style="flex:32;background:#edbb68"></span><span style="flex:600;background:#8064bc"></span></div><div class="budget-legend"><span>● R&D 1,774.14억</span><span>● 보조사업 32억</span><span>● 펀드 출자 600억</span></div><p class="small">합계 2,406.14억원. 원문 백만원을 100으로 나눠 환산했습니다. 펀드 민간자금 400억원은 이 정부안 합계에 포함하지 않습니다.</p><div class="budget-year-bars"><div><span>2026 본예산</span><i style="width:87.92%"></i><b>2,115.41억</b></div><div><span>2027 정부안</span><i style="width:100%"></i><b>2,406.14억</b></div></div></div><figure class="budget-image"><button id="open-budget-image"><img src="assets/mcst-2027.jpg" alt="문체부 2027 CT 생태계 예산 및 신규사업 요약 인포그래픽" loading="lazy"><span>첨부 인포그래픽 확대 ↗</span></button><figcaption>사용자 제공 문체부 인포그래픽 · 원자료: 문체부 2026.9.8 보도자료. 숫자는 본문 예산표와 대조.</figcaption></figure></div>
<details><summary>분야별 R&D 예산 비교 · 저작권 분야는 감소</summary><p>단위: 억원. 기획·평가 등을 포함한 R&D 합계입니다. 분야 총액과 개별 신규사업액을 중복 합산하지 않습니다.</p><div class="table-wrap"><table><thead><tr><th>분야</th><th>2026 본예산</th><th>2027 정부안</th><th>공식 증감률</th></tr></thead><tbody>${CT_BUDGET.sectors.map(s=>`<tr><td>${s.name}</td><td>${s.before.toLocaleString()}</td><td>${s.after.toLocaleString()}</td><td>${s.rate>0?'+':''}${s.rate}%</td></tr>`).join('')}<tr><th>R&D 합계</th><td>1,515.41</td><td>1,774.14</td><td>+17.1%</td></tr></tbody></table></div><p class="small">문체부 보도자료 1쪽. AI 저작권 신규사업이 있어도 저작권 분야 총액은 203.22 → 176억원으로 감소합니다.</p></details>
<div class="section-heading"><div><p class="eyebrow">PROGRAM EXPLORER</p><h2>신규사업과 우리 역할을 연결하기</h2></div><label>지원 방식<select id="fund-kind"><option value="">전체</option><option>R&D</option><option>보조사업</option><option>펀드</option></select></label></div><p>사업 카드를 선택하면 공동기획 과제·파트너·진입 조건이 표시됩니다. 제안된 참여 역할은 미협약 상태입니다.</p><div class="fund-explorer"><div id="fund-cards"></div><article id="fund-detail" aria-live="polite"></article></div>
<h2>타부처 연계는 역할과 비용을 나누어 설계</h2><div class="ministry-flow"><button data-ministry="education">교육부<small>공유교육 · 인재</small></button><span>→</span><button data-ministry="culture">문체부<small>문화기술 · 현장</small></button><span>↔</span><button data-ministry="science">과기정통부 등<small>AI 기반 · 지역 AX</small></button><span>→</span><button data-ministry="business">중기부 등<small>기업 성장 · 사업화</small></button></div><div id="ministry-detail" class="route-detail" aria-live="polite"></div>
<details><summary>국가 R&D 편성안에서 읽은 연결 근거와 한계</summary><div class="table-wrap"><table><thead><tr><th>정책 신호</th><th>2027년 안</th><th>실감미디어 연결 제안 / 원문</th></tr></thead><tbody><tr><td>AI R&D</td><td>4.1조원</td><td>공간·멀티모달 AI 기반 연구. 별지 5·7쪽</td></tr><tr><td>피지컬AI 핵심기술</td><td>신규 550억원</td><td>합성데이터·가상/실세계 검증과 XR 시뮬레이션의 접점. XR 콘텐츠 제작만으로 부합하지 않음. 7쪽</td></tr><tr><td>지역 R&D / 지역 자율형</td><td>4.5조원 / 0.55조원</td><td>권역 전략산업·지역 주관체계에 맞는 실증. 자율형은 지역 R&D에 포함되는 범위로 별도 합산 금지. 11쪽</td></tr><tr><td>지역 AX</td><td>전북 1,457억 · 대구 643억 등</td><td>자동차·바이오/로봇 등 해당 산업과 기술요건에 맞을 때만 산업훈련 협력 검토. 11쪽</td></tr><tr><td>투자연계기술개발</td><td>1,661억원</td><td>스케일업TIPS·글로벌TIPS 중 정책지정형. 대학 지원예산이 아닌 기업 성장 연계 후보. 10쪽</td></tr><tr><td>청년·인재</td><td>1.8조원</td><td>학부 공동교육과 석박사 연구를 역할별 연결. 12쪽</td></tr></tbody></table></div><p>국가 편성안의 분야 통계에는 중복이 존재합니다. AI·지역·인재 예산을 합쳐 ‘지원 가능한 총액’으로 계산하지 않습니다. 지역 통계 범위도 재정비되었으므로 증가를 전부 신규 가용재원으로 해석하지 않습니다.</p>${sourceLinks(['S30'])}</details>
<h2>2027 진입 준비 · 공모 확정 전 할 일</h2><div class="grid3"><article class="card"><span class="badge plan">지금 · 2026년 하반기</span><h3>기술·권리·수요 확인</h3><p>라이브·뮤지엄 후보별 기술명세, 성능 기준선, 권리자와 실증기관을 확보합니다. 기존 COSS 성과의 사업 귀속과 재사용 권리를 먼저 확인합니다.</p></article><article class="card"><span class="badge plan">국회 확정·RFP 이후</span><h3>자격·규모에 맞춰 재편</h3><p>최종 예산, 과제 수, 과제당 지원액, 주관기관 자격, 매칭·기간·성과요건을 확인합니다. 공식 공모 전에는 선정 가능성·배정액을 수치로 약속하지 않습니다.</p></article><article class="card"><span class="badge plan">선정·협약 이후</span><h3>실증에서 후속 활용으로</h3><p>교육·R&D·사업화의 비용과 산출물 원장을 나눕니다. 비교실증을 통과한 기술부터 보조사업·투자 경로를 검토합니다.</p></article></div>
<div class="note"><b>공모 세부조건: 향후 입력</b><p>공고번호 · 접수기간 · 주관/공동기관 자격 · 과제당 지원액 · 민간부담 · 지원기간 · TRL · 평가항목은 이번 자료에서 확정하지 않았습니다. 정부안 → 확정예산 → 공고/RFP → 협약 단계를 구분해 갱신합니다.</p></div><p><a href="proposal-2027.md" download>2027 부처 연계 상세 제안서 내려받기 ↗</a> · <a href="assets/mcst-2027-release.pdf" target="_blank">문체부 공식 보도자료 PDF</a> · <a href="assets/national-budget-2027.pdf" target="_blank">제공된 국가 R&D 예산안 PDF</a></p>`;
$('main').append(fundSection);sections.splice(sections.findIndex(s=>s[0]==='future'),0,['funding','2027 R&D']);
$('nav').innerHTML=sections.map(([id,label])=>`<a href="#${id}" data-section="${id}">${label}</a>`).join('');
let selectedProgram='live';
function showProgram(id){selectedProgram=id;const p=FUNDING_PROGRAMS.find(p=>p.id===id);$('#fund-detail').innerHTML=`<span class="badge plan">정부 예산안 · ${p.kind}</span><h3>${p.name}</h3><strong class="program-amount">${p.amount.toLocaleString()}억원 <small>2027년 사업 전체</small></strong><p><b>확인된 사업 방향</b><br>${p.purpose}</p><p><b>휴먼–AI–XR 연결 제안</b><br>${p.proposal}</p><p><b>함께할 주체 · 미협약</b><br>${p.partners}</p><p><b>진입 조건</b><br>${p.gate}</p><p><b>제안 산출물</b><br>${p.deliverable}</p><p class="small">문체부 공식 PDF ${p.page}</p>${sourceLinks([p.source])}`;document.querySelectorAll('[data-program]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.program===id)))}
function drawPrograms(){const a=FUNDING_PROGRAMS.filter(p=>!$('#fund-kind').value||p.kind===$('#fund-kind').value);$('#fund-cards').innerHTML=a.map(p=>`<button data-program="${p.id}"><span>${p.kind} · ${p.priority}</span><b>${p.name}</b><strong>${p.amount.toLocaleString()}<small>억원 · 정부안</small></strong></button>`).join('');document.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>showProgram(b.dataset.program));showProgram(a.some(p=>p.id===selectedProgram)?selectedProgram:a[0].id)}
$('#fund-kind').onchange=drawPrograms;drawPrograms();
const ministries={education:['교육 기반 · 교육부 앵커·공유대학','거점국립대 주관 공동교육과 지역학생 역량·정주를 담당하도록 제안합니다. 기존 COSS는 공동교과·공간·전문교원을 연결합니다. 2026년 공유대학 1,200억원을 2027년 확정예산으로 이월 표기하지 않습니다.','공동교과·학점인정·실습·학생 지원을 교육 원장에 기록. 문체부 기술개발비와 동일 비용 중복 집행 방지.',['S25']],culture:['주 연구개발 경로 · 문체부','실감미디어 정체성과 직접 연결되는 라이브·뮤지엄을 우선 기획하고, 기술 성숙도에 따라 현장솔루션을 검토합니다. AI 저작권은 공통 연구 협력 모듈입니다.','대학·기업·문화기관이 기술·IP·현장과 검증을 분담. 기업주도형 또는 기관 자격은 개별 RFP에 따름.',['S29']],science:['선별적 기술 협력 · 과기정통부·지역 산업 R&D','국가 편성안의 AI·월드모델·지역 AX와 연결할 수 있으나 독립된 연구 문제와 산업 수요가 필요합니다. K-뮤지엄의 K-Science 선정은 정책 연계 근거이며 별도 과기정통부 재원을 추가 확보했다는 뜻은 아닙니다.','산업훈련 트랙은 기존 성장엔진 기업 수요와 연결. 원천 AI 연구, 문화 응용, 직무교육의 목표·데이터·비용을 구분.',['S30','S29','S27']],business:['후속 성장 경로 · 기업 지원·투자','기술·IP·고객을 갖춘 기업은 투자연계기술개발 등 기업 성장 경로를 검토할 수 있습니다. 부처·전문기관·투자 선행조건과 해당 공고의 자격을 확인한 뒤 선택합니다.','문체부 사업화 보조·CT 펀드와도 단계별 비교. 보조금, 연구개발 출연, 지분 투자는 다른 수단이며 자동 연속 선정되지 않음.',['S30','S29']]};
function showMinistry(k){let m=ministries[k];$('#ministry-detail').innerHTML=`<h3>${m[0]}</h3><p>${m[1]}</p><p><b>분담할 업무</b><br>${m[2]}</p>${sourceLinks(m[3])}`;document.querySelectorAll('[data-ministry]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.ministry===k)))}
document.querySelectorAll('[data-ministry]').forEach(b=>b.onclick=()=>showMinistry(b.dataset.ministry));showMinistry('culture');
$('#open-budget-image').onclick=()=>{chartDialog.querySelector('h2').textContent='2027 문체부 CT 생태계 예산안';chartDialog.querySelector('img').src='assets/mcst-2027.jpg';chartDialog.querySelector('img').alt='사용자 제공 문체부 CT 예산안 인포그래픽';const links=chartDialog.querySelectorAll('a');links[0].href='assets/mcst-2027.jpg';links[1].href=FUNDING_SOURCES[0].url;links[1].textContent='문체부 출처';chartDialog.showModal()};
document.querySelectorAll('[data-chart]').forEach(b=>b.addEventListener('click',()=>{const a=chartDialog.querySelectorAll('a')[1];a.href='https://coss.ac.kr/intro/intro_realistic';a.textContent='COSS 출처'}));
// Keep original educational proposal accessible, but lead with the integrated proposal.
const prior=document.createElement('details');prior.innerHTML='<summary>교육부 앵커·공유대학 연계 기반과 기존 실행안</summary>';policyBlock.before(prior);prior.append(policyBlock);
const integrated=document.createElement('div');integrated.innerHTML=`<div class="thesis"><p class="eyebrow" style="color:#8be5d0">2027 통합 제안 · 미협약</p><h3>휴먼–AI–XR 실감융합 공유캠퍼스<br>× K-컬처 경험혁신 공동연구 네트워크</h3><p>교육부의 공유교육을 인재 기반으로, 문체부의 라이브·뮤지엄 기술개발을 핵심 연구 경로로 연결합니다. 지역 산업훈련은 기존 성장엔진 수요에 맞춘 별도 트랙으로 유지하고, 검증된 성과만 사업화·투자로 이어갑니다.</p><a href="#funding">2027 예산과 사업별 연결 근거 보기 →</a> · <a href="proposal-2027.md" download>상세 제안서 ↗</a></div><div class="grid3"><article class="strategy"><span class="number">FLAGSHIP 01</span><h3>사람 중심 라이브 경험</h3><p>공간별 영상·음향과 AI 연출을 결합하고 실제 관객의 몰입·접근성·지연·운영비를 비교 검증합니다.</p><b>문체부 K-라이브 연계 제안</b></article><article class="strategy"><span class="number">FLAGSHIP 02</span><h3>근거 있는 뮤지엄 AI–XR</h3><p>학예 검수와 문화자원 지식을 바탕으로 AI 에이전트·공간 자산·다국어 경험을 연구합니다.</p><b>문체부 K-뮤지엄 연계 제안</b></article><article class="strategy"><span class="number">COMMON FOUNDATION</span><h3>권리·평가·재사용</h3><p>디지털 휴먼·공연·문화자산의 권리 이력, 학습과 현장 효과, 기관 간 재사용을 공통 기준으로 관리합니다.</p><b>저작권 기술·기업 사업화 연결</b></article></div><p class="small">기존 연 10억원 산정 예시는 공유캠퍼스 착수 시나리오이며, 위 다부처 R&D를 포함한 총사업비가 아닙니다. 각 공고의 기간·지원액·분담금을 확인한 뒤 별도 예산안을 산정합니다.</p>`;
$('#recommendations').prepend(integrated);
overview.querySelector('.hero').insertAdjacentHTML('afterend','<a class="fund-banner" href="#funding"><span>NEW · 2027 정부 예산안 분석</span><b>문체부 CT 2,406억원, 휴먼–AI–XR는 어디에 연결할까?</b><span>예산·부처 연계 탐색 →</span></a>');
overview.querySelector('.stat-strip>div:last-child strong').textContent=SOURCES.length;
$('#bibliography').insertAdjacentHTML('beforeend',FUNDING_SOURCES.map(s=>`<p><b>${s.id}</b> · <a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><br><span class="small">${s.date} · 확인 ${s.accessed}</span></p>`).join(''));
showSection();
