const FUNDING_SOURCES=[
{id:'S29',title:'문체부 · 2027 문화기술 생태계 정부 예산안 및 신규사업 개요',date:'2026-09-08',url:'https://www.mcst.go.kr/site/s_notice/press/pressView.jsp?pSeq=22695',accessed:'2026-09-29'},
{id:'S30',title:'국가과학기술자문회의 · 2027 국가연구개발사업 예산 편성(안) · 사용자 제공 원문',date:'2026-08-31',url:'assets/national-budget-2027.pdf',accessed:'2026-09-29'},
{id:'S31',title:'아시아경제 · 문화기술 투자 확대, 내년 예산 2406억원',date:'2026-09-08',url:'https://view.asiae.co.kr/article/2026090819132578518',accessed:'2026-09-29'}
];
SOURCES.push(...FUNDING_SOURCES);
// Unit: KRW 100 million. Exact conversions from MCST table (KRW million).
const CT_BUDGET={total2026:2115.41,total2027:2406.14,rd2026:1515.41,rd2027:1774.14,subsidy:32,fund:600,
 sectors:[{name:'콘텐츠·문화예술',before:1135.53,after:1390.28,rate:22.4},{name:'저작권',before:203.22,after:176,rate:-13.4},{name:'체육',before:65.25,after:87,rate:33.3},{name:'관광',before:37.5,after:50,rate:33.3},{name:'기획·평가 등',before:73.91,after:70.86,rate:-4.1}]};
const FUNDING_PROGRAMS=[
{id:'live',ministry:'문체부',kind:'R&D',name:'K-컬처 라이브 공연향유 경험혁신 기술개발',amount:250,priority:'우선 기획',source:'S29',page:'2·7쪽',purpose:'AI 연출과 원격공간 최적화로 공연·스포츠 현장의 몰입감을 전달하는 기술.',proposal:'Human–AI–XR 라이브 경험 공동연구: 관객 경험 평가, 공간별 화면·음향 적응, AI 연출의 일관성과 지연 검증.',partners:'공연·방송/플랫폼 기업 + 공연장·상영관 + XR·디자인 대학 연구팀. 총괄 신청기관은 공고 확인 후 결정.',gate:'공연 IP·촬영/전송 권리, 라이브 데이터, 2개 이상 실제 공간의 비교실증 가능성부터 협의. 250억원은 사업 전체 2027년 정부안.',deliverable:'AI 연출 시제품, 공간별 재현 평가, 접근성 평가와 운영비 모델.'},
{id:'museum',ministry:'문체부',kind:'R&D',name:'전통의 재가치화를 통한 K-뮤지엄 글로벌 선도 기술개발',amount:62,priority:'우선 기획',source:'S29',page:'2–3·8쪽',purpose:'박물관 자원의 탐사·AI 보존관리·데이터 전환·콘텐츠 활용을 연결.',proposal:'근거를 제시하는 문화자원 AI 에이전트와 재사용 가능한 XR 서사·공간 자산 연구. 컨소시엄 강점에 맞는 콘텐츠 활용 부분부터 공동기획.',partners:'박물관·미술관 + 문화유산/보존 전문기관 + AI·콘텐츠 기업 + 대학. 탐사·보존 전문성은 별도 협력 확보.',gate:'유물·이미지·메타데이터 사용권, 학예사 검수, 다국어·접근성 실증. 일반 가상전시 제작만으로 사업 전주기 요구를 충족한다고 보지 않음.',deliverable:'출처가 연결된 문화지식·에이전트, XR 콘텐츠, 학예 검수·환각 평가셋.'},
{id:'solution',ministry:'문체부',kind:'R&D',name:'K-컬처 현장솔루션 기술개발',amount:50,priority:'단기 진입 검토',source:'S29',page:'3·8쪽',purpose:'기업주도 1년 현장형 과제와 공공기술 이전·개선 중심 2년 도약형 과제의 자유공모 방향.',proposal:'COSS 대학의 기존 기술 중 귀속·성능·권리가 확인된 것 한 가지를 기업 애로 해결 과제로 전환.',partners:'수요·사업화 기업 중심 + 기술 보유 대학/TLO. 교육용 작품과 이전 가능한 연구기술을 먼저 구분.',gate:'이전 대상 기술·권리·기업 고객 문제·개선 성능을 명확히 해야 함. 예산안의 자유공모 방향은 실제 접수 개시를 뜻하지 않음.',deliverable:'기능 개선 시제품, 기술이전/사용 계약, 현장 성능 및 도입 증빙.'},
{id:'rights',ministry:'문체부',kind:'R&D',name:'AI 저작권 신뢰 거버넌스 기술개발',amount:31,priority:'공통 기반 협력',source:'S29',page:'3·9쪽',purpose:'AI 학습데이터의 권리·출처 검증과 생성 기여도·라이선싱·정산 기술.',proposal:'공연·문화자원·디지털 휴먼의 권리 이력과 기여 검증을 연구하는 공통 모듈. 단순 출처 표기 DB와 연구개발을 구분.',partners:'저작권·AI 기술 전문기업/기관 + 권리자 + 대학 연구팀.',gate:'권리자 동의와 평가 데이터, 오류·기여도 검증 방법 필요. 해당 신규사업 31억원과 저작권 분야 총예산 증가를 동일시하지 않음.',deliverable:'권리 메타데이터, 검증 프로토타입, 정산 시뮬레이션과 평가 보고.'},
{id:'market',ministry:'문체부',kind:'보조사업',name:'K-문화기술 글로벌 사업화 및 시장창출 지원',amount:32,priority:'성과 확보 후',source:'S29',page:'4·10쪽',purpose:'문화기술과 콘텐츠 IP의 상용화, 테크 세일즈·해외시장 연결.',proposal:'검증된 라이브·뮤지엄 기술을 수요처의 IP와 결합해 고객 검증·판로·해외 시범 적용으로 확장.',partners:'기술 사업화 기업 + IP 보유자 + 현지 수요기관. 대학은 기술 제공·검증 파트너.',gate:'어떤 R&D 성과가 지원 대상인지, 신청 자격과 매칭 조건은 공고에서 확인. COSS 교육성과가 자동 대상이 되지는 않음.',deliverable:'유료 실증·구매 의향, 수출/판매 계약, 유지운영 계획.'},
{id:'fund',ministry:'문체부',kind:'펀드',name:'문화기술(CT) 펀드',amount:600,priority:'투자 준비 후',source:'S29',page:'1·4쪽',purpose:'2027년 정부 출자 예산안 600억원. 민간 400억원을 더한 약 1,000억원 조성 계획.',proposal:'법인·IP·매출 모델을 갖춘 사업화 기업이 운용사의 투자 심사를 준비. 대학 사업단 연구비와 분리.',partners:'사업화 법인 + 펀드 운용사·투자자. 실제 운용계획과 투자대상 조건 확인.',gate:'조성규모는 2027년 1월 운용계획 등에서 확정 예정이며 변동 가능. 1,000억원을 추가 정부 예산으로 합산하지 않음.',deliverable:'투자 실사자료, 권리·재무·고객 검증 자료. 투자 유치 보장 없음.'}
];
