const iitpSection=document.createElement('section');iitpSection.id='iitp';
iitpSection.innerHTML=`<div class="iitp-hero"><p class="eyebrow">HUMAN–AI–XR · CORE TECHNOLOGY & TALENT</p><h1>사람을 이해하는 AI,<br>현장과 연결되는 실감미디어.</h1><p>교육부의 인재 기반에 IITP의 핵심기술 연구를 더하고,<br>문체부의 문화현장에서 가치를 검증하는 후속사업 제안</p><span class="budget-status">공식 사업 소개: 2026년 · 검토일 2026.09.29</span></div>
<div class="budget-kpis"><article><small>실감콘텐츠핵심기술개발 · 2026</small><strong>267.12<em>억원</em></strong><p>총 30개 · 신규 20 / 계속 10<br>대학·연구기관·기업 등 지원 대상</p></article><article><small>가상융합대학원 · 2026</small><strong>65.01<em>억원</em></strong><p>계속과제 8개 · 평균 약 8억원<br>신규 모집이 확인된 상태 아님</p></article><article><small>2027 IITP 예산·신규 공모</small><strong class="iitp-pending">향후 입력</strong><p>이번에 확인한 소개 자료로는 미확정<br>2027 문체부 예산안과 합산하지 않음</p></article></div>
<p class="small">사업 전체 규모이며 컨소시엄 확보액이 아닙니다. 핵심기술개발의 과제당 평균 8.9억원은 신청 상한액이 아닙니다. 아래 세 기술 트랙은 267.12억원의 구성 사업이므로 각각에 같은 총액을 배정하지 않습니다. ${sourceLinks(['S32','S33'])}</p>
<h2>하나의 비전, 네 가지 진입 경로</h2><p>버튼을 선택해 공식 사업 방향과 우리가 제안하는 과제를 구분해서 살펴보세요.</p><div class="iitp-tabs">${IITP_ROUTES.map(r=>`<button data-iitp="${r.id}" aria-pressed="false">${r.label}</button>`).join('')}</div><article id="iitp-detail" class="route-detail" aria-live="polite"></article>
<h2>교육–핵심기술–현장실증을 연결하는 구조</h2><div class="iitp-chain"><a href="#future"><span>교육부 · 앵커/공유대학</span><b>사람과 교육을 연결</b><small>공동교과 · 학점 · 지역 수요</small></a><a href="#iitp"><span>과기정통부 · IITP</span><b>재사용할 기술을 연구</b><small>AI·XR 엔진 · 인터페이스 · 석박사</small></a><a href="#funding"><span>문체부 · CT</span><b>문화현장에서 검증</b><small>라이브 · 뮤지엄 · 권리 · 사업화</small></a></div><p class="small">분석자가 제안한 연계 구조입니다. 부처 간 통합공모나 연속 선정이 확정된 사업이 아닙니다. 공통 자산의 사용권을 정하고 연구목표·산출물·회계는 과제별로 구분합니다.</p>
<div class="grid3"><article class="card"><span class="badge plan">우선 기획</span><h3>공간경험 엔진 × K-컬처</h3><p>IITP에는 기기 간 공간·감각 정합과 AI 상호작용의 기술 문제를, 문체부에는 라이브·뮤지엄의 경험혁신과 현장 성능을 제안합니다. 동일 시제품·인건비를 이중 계상하지 않습니다.</p></article><article class="card"><span class="badge plan">수요 확보 후</span><h3>숙련전수 × 지역 성장엔진</h3><p>앵커사업의 기업 수요를 출발점으로 숙련의 디지털 획득과 훈련 피드백을 연구합니다. 기업 수요서·공정 데이터 사용권·비교실증 설계가 확보된 분야부터 추진합니다.</p>${sourceLinks(['S27'])}</article><article class="card"><span class="badge plan">협약 검토</span><h3>공유교육 × 연구인재</h3><p>기존 가상융합대학원과 공동 프로젝트를 먼저 협의합니다. 신규 대학원 사업 신청은 후속 공고가 열리고 자격이 확인될 때 검토합니다.</p></article></div>
<details><summary>90일 준비안 · 선정 전에 확보할 증거</summary><ol><li><b>1–30일:</b>7개교 보유기술·논문·특허·연구자·장비 목록과 권리를 확인. 기술별 주관 후보, 기업 문제, 기존 대학원 협력 대상을 정리.</li><li><b>31–60일:</b>공간경험·숙련전수 중 우선 과제의 기준선 실험. 기업·문화기관의 수요서와 데이터 이용 조건 확보.</li><li><b>61–90일:</b>공고/RFP와 연구목표 대조, 기관 자격·부담금·TRL·기간 검토. 교육부/IITP/문체부별 산출물·비용 구분표와 기획서 작성.</li></ol><p>기간은 착수 시점부터의 제안 일정입니다. 공모 일정이나 선정 보장이 아닙니다. 성능 목표 수치는 사전실험 후 설정합니다.</p></details>
<details><summary>신규 공모 확인표 · 아직 확정하지 않은 내용</summary><p>2027 공고번호·RFP·접수기간·주관기관 자격·과제당 지원액·지원기간·민간부담·TRL·성과요건: <b>향후 입력</b>.</p><p>사업 소개는 모집 공고가 아닙니다. 2026 신규과제 수를 현재 신청 가능한 잔여 물량으로 읽지 않습니다. IITP 사업공고 및 IRIS의 해당 공고 원문을 대조한 뒤 갱신합니다.</p><a href="https://www.iitp.kr/web/lay1/program/S1T44C51/iris/list.do" target="_blank" rel="noopener">IITP 공식 사업공고 확인 ↗</a></details><p><a href="proposal-iitp.md" download>IITP 연계 상세 제안서 내려받기 ↗</a> · ${sourceLinks(['S32','S33','S34'])}</p>`;
$('main').append(iitpSection);sections.splice(sections.findIndex(s=>s[0]==='future'),0,['iitp','IITP 연계']);$('nav').innerHTML=sections.map(([id,label])=>`<a href="#${id}" data-section="${id}">${label}</a>`).join('');
function showIitp(id){const r=IITP_ROUTES.find(r=>r.id===id);$('#iitp-detail').innerHTML=`<div class="iitp-detail-grid"><div><span class="badge">공식 사업 방향</span><h3>${r.name}</h3><p>${r.fact}</p>${sourceLinks([r.source])}<p><b>진입 조건·한계</b><br>${r.gate}</p></div><div><span class="badge plan">후속사업 제안 · 미협약</span><h3>${r.proposal.split(':')[0]}</h3><p>${r.proposal}</p><p><b>협력 주체</b><br>${r.partners}</p><p><b>산출물·평가</b><br>${r.outputs}</p></div></div>`;document.querySelectorAll('[data-iitp]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.iitp===id)))}
document.querySelectorAll('[data-iitp]').forEach(b=>b.onclick=()=>showIitp(b.dataset.iitp));showIitp('core');
ministries.science=['핵심기술·연구인재 경로 · 과기정통부/IITP','실감콘텐츠핵심기술개발의 AI·XR·공간컴퓨팅을 주요 연구 경로로 검토합니다. 가상융합대학원은 기존 수행기관과 연구인재 협력을 우선 추진합니다.','IITP는 재사용 가능한 기반기술, 문체부는 문화현장의 응용·검증, 교육부는 공동교육을 분담하도록 제안합니다. 2026 사업 규모와 2027 예산안을 혼합하지 않습니다.',['S32','S33']];
ministries.culture[0]='문화현장 응용·실증 경로 · 문체부';
$('[data-ministry="science"]').innerHTML='과기정통부·IITP<small>AI·XR 핵심기술 · 연구인재</small>';
integrated.querySelector('.thesis h3').innerHTML='휴먼–AI–XR 실감융합 공유캠퍼스<br>× 공간경험 기술·문화현장 공동연구 네트워크';
integrated.querySelector('.thesis>p:not(.eyebrow)').textContent='교육부의 공유교육을 기반으로, IITP의 AI·XR 핵심기술·연구인재와 문체부의 라이브·뮤지엄 경험혁신을 연결합니다. 지역 성장엔진의 숙련전수 수요를 별도 트랙으로 검토하고, 과제별 목표·성과·비용을 구분해 기획합니다.';
integrated.querySelector('.thesis').insertAdjacentHTML('beforeend','<p><a href="#iitp">IITP 핵심기술·대학원 연계와 실행 조건 보기 →</a></p>');
overview.querySelector('.hero').insertAdjacentHTML('afterend','<a class="fund-banner iitp-banner" href="#iitp"><span>NEW · IITP 공식 사업 분석</span><b>휴먼–AI–XR, 핵심기술과 석박사 연구까지 연결하다</b><span>4개 진입 경로 탐색 →</span></a>');
overview.querySelector('.stat-strip>div:last-child strong').textContent=SOURCES.length;
$('#bibliography').insertAdjacentHTML('beforeend',IITP_SOURCES.map(s=>`<p><b>${s.id}</b> · <a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><br><span class="small">${s.date} · 확인 ${s.accessed}</span></p>`).join(''));showSection();
