const fullTitle='실감미디어혁신공유대학 성과분석 및 후속 사업 제언';
document.title=fullTitle;
$('.brand').innerHTML='실감미디어혁신공유대학<small>성과분석 및 후속 사업 제언</small>';
$('footer').innerHTML=`${fullTitle}<br><small>공개 근거 기반 독립 분석 · 공식 사업단 웹사이트가 아닙니다. 이미지·로고 권리는 각 기관에 있습니다.</small>`;
const logoBase='https://www.xr.ac.kr/modules/xr/templets/default/images/';
const logoFiles=['img_intro_universities01_2025.svg','ico_main_sec5_2.png','ico_main_sec5_3.png','ico_main_sec5_7.png','ico_main_sec5_4.png','ico_main_sec5_5.png','ico_main_sec5_6.png'];
const charts=[['realistic_img03.png','7개 대학의 특성과 강점','대학별 전문성이 어떻게 연결되는지 살펴봅니다.'],['realistic_img02_1.png','인재상·역량·마이크로디그리','교육목표와 교육과정의 관계를 확인합니다.'],['realistic_img04.jpg','X-SPACE 교육 체계','공유 공간을 통한 실감미디어 교육 구상입니다.']];
const overview=document.createElement('section');overview.id='overview';
overview.innerHTML=`<div class="hero"><div><p class="eyebrow">IMMERSIVE MEDIA · EVIDENCE & NEXT</p><h1>실감미디어혁신공유대학<br><span>성과분석 및 후속 사업 제언</span></h1><p>공유교육의 성과를 읽고,<br>휴먼–AI–XR의 다음 가능성을 연결합니다.</p><div class="hero-actions"><a href="#explore">성과 지도 탐색 ↗</a><a href="#future">후속사업 제언 보기 →</a></div><small>2021–2025 공개자료 분석 · 정책 보완 2026.09.29</small></div><div class="orbit" aria-label="휴먼 AI XR 융합 개념도, 분석 제안"><div class="orbit-core">실감미디어<small>AI 융합</small></div><span class="orb human">HUMAN<small>학습 · 경험</small></span><span class="orb ai">AI<small>생성 · 피드백</small></span><span class="orb xr">XR<small>공간 · 상호작용</small></span><p>후속사업 설계 개념</p></div></div><div class="stat-strip"><div><strong>7</strong><span>컨소시엄 대학</span></div><div><strong>5</strong><span>분석 대상 연도</span></div><div><strong>19</strong><span>기간 내 수록 기록 · 실적 총계 아님</span></div><div><strong>28</strong><span>성과·정책·기술 출처</span></div></div><h2>7개 대학, 연결되는 전문성</h2><p class="small">로고를 선택하면 해당 대학의 공개기록으로 이동합니다. 로고 출처: <a href="https://www.xr.ac.kr/ko/" target="_blank" rel="noopener">공식 사업단 홈페이지</a></p><div class="university-grid">${officialRoles.map((u,i)=>`<button class="university-tile" data-school="${u[0]}"><img src="${logoBase+logoFiles[i]}" alt="${u[0]} 로고" loading="lazy"><b>${u[0]}</b><small>${u[1]}</small></button>`).join('')}</div><div class="section-heading"><div><p class="eyebrow">OFFICIAL VISUAL ARCHIVE</p><h2>공식 도표로 보는 사업 구조</h2></div><a href="https://coss.ac.kr/intro/intro_realistic" target="_blank" rel="noopener">COSS 원문 ↗</a></div><div class="visual-gallery">${charts.map((c,i)=>`<button class="visual-card" data-chart="${i}"><div class="image-frame"><img src="https://coss.ac.kr/intro_img/${c[0]}" alt="${c[1]} 공식 도표" loading="lazy"></div><span>0${i+1} / COSS 공식 자료</span><h3>${c[1]} ↗</h3><p>${c[2]}</p></button>`).join('')}</div><p class="small">출처: COSS 실감미디어 소개. 원본의 구상·역할을 보여주는 자료이며, 시설 운영 실적이나 성과 총계를 의미하지 않습니다.</p>`;
$('main').prepend(overview);
const sections=[['overview','개요'],['explore','성과 탐색'],['compare','대학별 분석'],['trajectory','연구 흐름'],['future','후속 제언'],['entry','자료 입력'],['sources','출처']];
$('nav').innerHTML=sections.map(([id,label])=>`<a href="#${id}" data-section="${id}">${label}</a>`).join('');$('.brand').href='#overview';
function showSection(){let id=location.hash.slice(1);if(!sections.some(s=>s[0]===id))id=location.search?'explore':'overview';sections.forEach(([key])=>{const el=document.getElementById(key);if(el)el.hidden=key!==id});document.querySelectorAll('[data-section]').forEach(a=>{if(a.dataset.section===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});}
window.addEventListener('hashchange',showSection);
document.querySelectorAll('[data-school]').forEach(b=>b.onclick=()=>{fields.forEach(k=>$('#'+k).value='');$('#university').value=b.dataset.school;update();location.hash='explore';showSection()});
document.querySelectorAll('[data-uni],[data-jump]').forEach(b=>{const old=b.onclick;b.onclick=()=>{location.hash='explore';showSection();old()}});
// Collapse detailed prose while keeping the main policy choices available.
const extra=document.createElement('details');extra.className='reading-panel';extra.innerHTML='<summary>연구·평가 원칙과 메타버스 시나리오 자세히 읽기</summary>';
while(policyBlock.nextSibling)extra.append(policyBlock.nextSibling);$('#recommendations').append(extra);
const comparisonExtra=document.createElement('details');comparisonExtra.innerHTML='<summary>대학별 공개사례와 5개년 기록 분포 자세히 보기</summary>';
const comparisonChildren=[...$('#comparison').children];comparisonChildren.slice(2).forEach(c=>comparisonExtra.append(c));$('#comparison').append(comparisonExtra);
$('#compare h2').textContent='대학별 역할과 성과 입력 현황';
const chartDialog=document.createElement('dialog');chartDialog.className='chart-dialog';chartDialog.innerHTML='<button class="dialog-close" aria-label="도표 닫기">닫기 ×</button><h2></h2><img alt=""><p><a target="_blank" rel="noopener">원본 이미지 열기 ↗</a> · <a href="https://coss.ac.kr/intro/intro_realistic" target="_blank" rel="noopener">COSS 출처</a></p>';
document.body.append(chartDialog);chartDialog.querySelector('button').onclick=()=>chartDialog.close();
document.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>{let c=charts[+b.dataset.chart],url='https://coss.ac.kr/intro_img/'+c[0];chartDialog.querySelector('h2').textContent=c[1];chartDialog.querySelector('img').src=url;chartDialog.querySelector('img').alt=c[1];chartDialog.querySelector('a').href=url;chartDialog.showModal()});
document.querySelectorAll('.university-tile img,.visual-card img').forEach(img=>img.onerror=()=>{img.hidden=true;const msg=document.createElement('span');msg.className='image-fallback';msg.textContent=img.alt+' · 원문에서 보기';img.after(msg)});
const entry=document.createElement('section');entry.id='entry';
const metrics=['논문','특허','석사 배출','박사 배출','기술이전','창업','산학관연'];
entry.innerHTML=`<p class="eyebrow">DATA WORKSPACE</p><h2>자료를 채우고, 근거를 연결합니다.</h2><p>미확인 항목은 <b>향후 입력</b>으로 표시합니다. 0건과는 다릅니다. 입력한 내용은 검증 전 초안이며 공개 성과 집계에 반영되지 않습니다.</p><div class="entry-layout"><form id="draft-form"><h3>성과 자료 입력</h3><div class="form-grid"><label>대학<select name="university">${UNIVERSITIES.map(u=>`<option>${u}</option>`).join('')}</select></label><label>연도<select name="year">${[2021,2022,2023,2024,2025,2026].map(y=>`<option>${y}</option>`).join('')}</select></label><label>항목<select name="metric">${metrics.map(m=>`<option>${m}</option>`).join('')}</select></label><label>수량<input name="value" type="number" min="0" step="1" required placeholder="향후 입력"></label></div><label>증빙 URL<input name="source" type="url" placeholder="https://… (선택)"></label><label>산정 기준·증빙 설명<textarea name="note" rows="3" maxlength="2000" placeholder="사업 귀속, 중복 제거, 자료명·쪽수 등을 기록하세요."></textarea></label><button type="submit" class="primary">이 브라우저에 초안 저장</button><p id="draft-status" role="status"></p><p class="small">이 기기·브라우저에만 저장됩니다. 공동 서버에 전송되지 않습니다. 브라우저 데이터 삭제 시 사라질 수 있으므로 JSON으로 백업하세요.</p></form><div><div class="entry-toolbar"><h3>저장된 입력 초안</h3><button id="draft-export">JSON 내보내기</button><label class="import-label">JSON 불러오기<input id="draft-import" type="file" accept="application/json,.json"></label></div><div id="draft-list"></div></div></div>`;
$('main').append(entry);
const storageKey='immersive-evidence-drafts-v1';let drafts=[];let storageOK=true;
function validDraft(d){return d&&UNIVERSITIES.includes(d.university)&&[2021,2022,2023,2024,2025,2026].includes(Number(d.year))&&metrics.includes(d.metric)&&Number.isSafeInteger(d.value)&&d.value>=0&&typeof d.source==='string'&&d.source.length<=2000&&(!d.source||/^https?:\/\//i.test(d.source))&&typeof d.note==='string'&&d.note.length<=2000;}
try{const a=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(a))drafts=a.filter(validDraft)}catch{storageOK=false}
function keyOf(d){return[d.university,d.year,d.metric].join('|')}
function persist(next){try{localStorage.setItem(storageKey,JSON.stringify(next));drafts=next;return true}catch{$('#draft-status').textContent='저장 공간을 사용할 수 없습니다. 입력값은 유지되어 있습니다.';return false}}
function editDraft(d){const f=$('#draft-form');for(const k of ['university','year','metric','value','source','note'])f.elements[k].value=d[k]??'';location.hash='entry';showSection();f.elements.value.focus()}
const pending=document.createElement('div');pending.className='pending-panel';$('#comparison').prepend(pending);
function drawDrafts(){pending.innerHTML=`<div class="section-heading"><div><h3>미확인 성과 채우기</h3><p class="small">5개년 확정 총계는 원장 확인 후 입력합니다. 입력 초안은 별도 보관됩니다.</p></div><a href="#entry">자료 입력으로 →</a></div><div class="pending-grid">${metrics.map(m=>`<button data-pending="${m}"><b>${m}</b><span>＋ 향후 입력</span><small>${drafts.filter(d=>d.metric===m).length}개 초안 저장</small></button>`).join('')}</div>`;pending.querySelectorAll('[data-pending]').forEach(b=>b.onclick=()=>editDraft({university:$('#university').value||UNIVERSITIES[0],year:2025,metric:b.dataset.pending}));$('#draft-list').innerHTML=drafts.length?drafts.map((d,i)=>`<article class="draft-row"><span class="badge plan">입력 초안 · 검증 전</span><h3>${esc(d.university)} · ${d.year} · ${esc(d.metric)} <strong>${d.value}${/배출/.test(d.metric)?'명':'건'}</strong></h3><p>${esc(d.note)||'산정 기준 향후 입력'}</p><p class="small">${d.source?esc(d.source):'증빙 향후 입력'}</p><button data-edit="${i}">수정</button><button data-remove="${i}">삭제</button></article>`).join(''):'<div class="empty">아직 저장된 초안이 없습니다. 대학·연도·항목을 선택해 첫 자료를 입력하세요.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editDraft(drafts[+b.dataset.edit]));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const previous=[...drafts];if(persist(drafts.filter((_,i)=>i!==+b.dataset.remove))){drawDrafts();$('#draft-status').innerHTML='초안을 삭제했습니다. <button type="button" id="undo-draft">되돌리기</button>';$('#undo-draft').onclick=()=>{if(persist(previous)){drawDrafts();$('#draft-status').textContent='삭제를 되돌렸습니다.'}}}})}
$('#draft-form').onsubmit=e=>{e.preventDefault();let f=e.currentTarget.elements,d={university:f.university.value,year:+f.year.value,metric:f.metric.value,value:Number(f.value.value),source:f.source.value.trim(),note:f.note.value.trim()};if(!validDraft(d)){$('#draft-status').textContent='입력 형식과 증빙 URL을 확인하세요.';return}const next=drafts.filter(x=>keyOf(x)!==keyOf(d));next.push(d);if(persist(next)){drawDrafts();$('#draft-status').textContent='초안을 저장했습니다. 같은 대학·연도·항목은 이 값으로 갱신됩니다.'}};
$('#draft-export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schema:1,status:'unverified-drafts',drafts},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='immersive-evidence-drafts.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#draft-import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error();const x=JSON.parse(await file.text());if(x.schema!==1||!Array.isArray(x.drafts)||x.drafts.length>1000||!x.drafts.every(validDraft))throw Error();const map=new Map(drafts.map(d=>[keyOf(d),d]));let added=0;for(const d of x.drafts)if(!map.has(keyOf(d))){map.set(keyOf(d),d);added++}if(persist([...map.values()])){drawDrafts();$('#draft-status').textContent=`${added}개 초안을 추가했습니다. 기존 동일 항목은 유지했습니다.`}}catch{$('#draft-status').textContent='올바른 초안 JSON 파일인지 확인하세요. 기존 자료는 유지됩니다.'}e.target.value=''};
drawDrafts();if(!storageOK)$('#draft-status').textContent='기존 저장 자료를 읽지 못했습니다. 저장 가능 여부를 확인하세요.';
showSection();
