// Broaden the successor proposal while retaining published evidence and old deep links.
const transition=document.createElement('section');transition.id='transition';
transition.innerHTML=`<div class="renew-hero"><p class="eyebrow">DEMOGRAPHY × INDUSTRY × LEARNING</p><h1>학생의 감소와 기술의 변화,<br>교육·연구의 구조를 다시 설계하다.</h1><p>실감미디어 전반을 대상으로 기초 제작, 시스템 통합, 현장 검증과 연구 역량을 함께 키웁니다. AI는 여러 기술과 결합하는 중요한 변화 요인입니다.</p><a href="#future">후속사업 설계 보기 →</a></div>
<div class="signal-grid"><article><span class="badge">인구 구조 · 공식 전망</span><h2>학령인구의 장기 감소</h2><div class="population-bars" role="img" aria-label="6~21세 학령인구: 2022년 750만명, 2040년 413만명 전망. 2022년 기준 추계."><div><label>2022 기준</label><i style="width:100%"></i><b>750만명</b></div><div><label>2040 전망</label><i style="width:55.07%"></i><b>413만명</b></div></div><p>2022년 기준 추계에서 337만명 감소 전망. 대학별 충원율이나 현재 재학생 수와는 다른 지표입니다.</p>${sourceLinks(['S35'])}<p class="implication">제안 → 학부·성인·재직자·연구자에게 열린 공동교육</p></article><article><span class="badge">노동시장 · 공식 분석</span><h2>경력 진입 과정의 변화</h2><strong class="signal-number">94<small>%</small></strong><p>한국은행 분석의 최근 4년 청년 일자리 감소 28.5만개 중 AI 고노출 업종의 감소분 기여율. 실감미디어 업종만의 수치가 아닙니다.</p><p class="small">AI 단독 인과효과로 해석할 수 없습니다. 기존 채용·업무 변화와 함께 읽어야 합니다.</p>${sourceLinks(['S36'])}<p class="implication">제안 → 멘토링·현장 프로젝트로 초기 경력을 쌓는 과정</p></article></div>
<h2>AI 기술의 진전과 남아 있는 연구 문제</h2><div class="grid3"><article class="card"><span class="badge">표준화 신호</span><h3>공간 데이터의 재사용</h3><p>Khronos는 2026년 2월 Gaussian Splatting의 glTF 확장 후보안을 발표했습니다. 이 발표만으로 최종 표준 채택을 단정하지 않습니다.</p>${sourceLinks(['S39'])}</article><article class="card"><span class="badge">실험적 기술</span><h3>생성되는 상호작용 세계</h3><p>Google은 Project Genie를 연구 프로토타입으로 소개합니다. 생성 세계의 제어·일관성과 현실 정확도는 별도 평가가 필요합니다.</p>${sourceLinks(['S40'])}</article><article class="card"><span class="badge plan">교육·연구 제안</span><h3>기초 + 통합 + 검증</h3><p>드로잉·모델링·코딩·사운드의 기초를 유지하면서 생성 도구, 엔진 통합, 최적화, 사용자 시험을 연결합니다. 모든 공정이 자동화되었다고 가정하지 않습니다.</p></article></div>
<div class="section-heading"><div><p class="eyebrow">RESEARCH PORTFOLIO · 분석 제안</p><h2>실감미디어 전반의 6개 연구·교육 영역</h2></div><span>특정 세 기술의 결합을 지원 조건으로 삼지 않습니다</span></div><div class="field-map">${RESEARCH_FIELDS.map(f=>`<button data-field="${f.id}" aria-pressed="false"><small>${f.icon}</small><b>${f.name}</b><span>${f.skills}</span></button>`).join('')}</div><article id="field-detail" class="route-detail" aria-live="polite"></article>
<h2>학습자별로 다른 진입과 성장 경로</h2><div class="learner-tabs">${LEARNER_PATHS.map(p=>`<button data-learner="${p.id}" aria-pressed="false">${p.label}</button>`).join('')}</div><article id="learner-detail" class="learner-panel" aria-live="polite"></article><p class="small">유학생에게는 언어·학업 적응·현장 참여 지원을 함께 설계합니다. 이수증의 누적이 자동 학위 취득이나 체류·취업 자격을 보장하지 않습니다.</p>
<details class="review-note"><summary>첨부 문서 검토 · 반영한 제안과 수정한 해석</summary><p>사용자 제공 「AI 전환기 실감미디어 인재양성 후속사업 방향」(2026.09.29)을 기획 자료로 검토했습니다. 정부 공식 계획과 분석자의 전망을 구분했습니다.</p><ul><li>성인·재직자 확대, 스튜디오 PBL, 기업 멘토링, 기초–통합–검증 역량과 성과 추적을 반영했습니다.</li><li>2,406억원은 2027 CT 생태계 전체 정부안이며 R&D는 약 1,774억원입니다.</li><li>AI 특화 콘텐츠 아카데미 192억원 표기는 채택하지 않았습니다. 확인한 KOCCA 2026 로드맵 본문은 79억원이며 서로 다른 범위·자료 여부를 추가 대조해야 합니다.</li><li>타 분야 사업단의 2027년 2월 종료 공지는 실감미디어 사업의 종료·학점교류 중단 확정 근거가 아닙니다.</li><li>AI 재도약대학 등 첨부 문서의 교육부 신규예산 수치는 이번 검토에서 공식 원문 대조를 완료하지 않아 확정 재원표에 넣지 않았습니다.</li><li>교과 40~50% 교체, 2~5인 창업, 2027~2031 기술 전망은 정책 확정치·성과 예측치가 아닌 기획 가설로 봅니다.</li></ul><a href="document-review.md" download>문서 검토 메모 내려받기 ↗</a> ${sourceLinks(['S41'])}</details>`;
$('main').append(transition);
function drawField(id){const f=RESEARCH_FIELDS.find(x=>x.id===id);$('#field-detail').innerHTML=`<span class="badge plan">연계 가능성 검토 · 선정·참여 미확정</span><h3>${f.name}: ${f.question}</h3><div class="grid3"><div><b>연구 질문과 검증</b><p>${f.research}</p></div><div><b>교육 역량</b><p>${f.education}</p></div><div><b>사업 연결</b><p>${f.route}</p><a href="#${f.target}">해당 부처 연계 탭 →</a></div></div>${sourceLinks(f.sources)}`;document.querySelectorAll('[data-field]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.field===id)))}
document.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>drawField(b.dataset.field));drawField('creation');
function drawLearner(id){const p=LEARNER_PATHS.find(x=>x.id===id);$('#learner-detail').innerHTML=`<h3>${p.title}</h3><ol class="learning-steps">${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p>${p.detail}</p><p><b>추적할 지표:</b> ${p.metric}</p><a href="#${p.link}">관련 인재양성 경로 확인 →</a>`;document.querySelectorAll('[data-learner]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.learner===id)))}
document.querySelectorAll('[data-learner]').forEach(b=>b.onclick=()=>drawLearner(b.dataset.learner));drawLearner('undergrad');

const linkage=document.createElement('section');linkage.id='linkage';
linkage.innerHTML=`<p class="eyebrow">MINISTRY CONNECTIONS · R&D & TALENT</p><h1>실감미디어 연구와 인재양성,<br>부처별 목적에 맞춰 연결합니다.</h1><p>콘텐츠·공간·디바이스·상호작용·서비스·신뢰 기술을 폭넓게 검토합니다. 공고의 연구 목적·기관 자격·지원 조건에 맞춰 과제를 구체화합니다.</p><div class="agency-tabs" role="tablist" aria-label="부처별 연계사업"><a href="#kocca" role="tab" id="tab-kocca" aria-controls="funding">문체부 · KOCCA<small>문화기술 연구 · 콘텐츠 인재</small></a><a href="#iitp" role="tab" id="tab-iitp" aria-controls="iitp">과기정통부 · IITP<small>핵심기술 연구 · 연구인재</small></a></div><div id="agency-panels"></div>`;
$('main').append(linkage);$('#agency-panels').append(fundSection,iitpSection);
fundSection.setAttribute('role','tabpanel');fundSection.setAttribute('aria-labelledby','tab-kocca');iitpSection.setAttribute('role','tabpanel');iitpSection.setAttribute('aria-labelledby','tab-iitp');
const koccaLead=document.createElement('div');koccaLead.className='agency-lead';koccaLead.innerHTML=`<p class="eyebrow">문체부 · 한국콘텐츠진흥원</p><h2>문화기술 R&D와 현장 인재양성의 두 경로</h2><p>연구개발 과제 참여와 교육운영기관·교육생 참여는 신청 방식이 다릅니다. 아래 2026년 자료는 후속 기획의 참고 근거이며 현재 모집 중임을 뜻하지 않습니다.</p><div class="grid3"><article class="card"><span class="badge">2026 추진계획 예고 · R&D</span><h3>문화기술 연구개발</h3><p>IP 기획·창작, 콘텐츠 제작, 문화서비스 기술을 포괄합니다. 실감미디어의 제작·공간·상호작용을 해당 연구 문제에 맞춰 제안합니다.</p>${sourceLinks(['S37'])}</article><article class="card"><span class="badge">2026 추진계획 예고 · 연구인재</span><h3>문화기술 전문인력 양성</h3><strong class="agency-amount">15억원 · 신규 2개</strong><p>장르별 CT 전문인력 양성 예고 규모입니다. 산학 공동연구·연구인재 경로로 검토하되 2027 계속·신규 지원은 별도 확인합니다.</p>${sourceLinks(['S37'])}</article><article class="card"><span class="badge">2026 교육 로드맵 · 실무인재</span><h3>예비 창작자부터 현업인까지</h3><p>AI 특화 콘텐츠 아카데미, 뉴콘텐츠아카데미, 창의인재동반사업 등을 교육 연계 후보로 검토합니다. 연구개발 출연금과 교육 지원을 구분합니다.</p>${sourceLinks(['S38'])}</article></div><details><summary>문화·관광·스포츠까지 확장할 수 있는 연구 주제</summary><p>2026 예고에는 공공문화시설 CT, 문화예술 온톨로지·LLM, 스포츠 데이터·융합서비스, AI 관광 기술도 포함됩니다. 전시·관광 경험, 운동 피드백, 데이터 시각화 등은 가능한 기획 예시이며 해당 RFP 적합성을 확인해야 합니다.</p>${sourceLinks(['S37'])}</details><p class="note">이 탭의 2027 예산은 문체부 발표 기준입니다. 모든 세부사업의 전담기관을 KOCCA로 일괄 확정하지 않으며 실제 공고에서 수행·관리기관을 확인합니다.</p></div>`;
fundSection.prepend(koccaLead);
fundSection.querySelector('.fund-hero').innerHTML='<p class="eyebrow">2027 문화기술 예산 · 정부안</p><h2>문화현장 연구·실증·사업화로 이어지는 경로</h2><p>기존 예산 분석을 유지하면서 실감미디어 전반의 연구와 인재양성 관점으로 연결합니다.</p><span class="budget-status">2027 정부 예산안 · 국회 확정 전</span>';
iitpSection.querySelector('.iitp-hero').innerHTML='<p class="eyebrow">과기정통부 · 정보통신기획평가원</p><h2>실감미디어 핵심기술과<br>석박사 연구인재를 함께 연결합니다.</h2><p>공간 재현·실감콘텐츠·인터페이스·센서·디바이스와 AI 융합 연구를 포괄합니다. 아래 과제 예시는 정부사업의 전체 범위를 제한하지 않습니다.</p><span class="budget-status">공식 사업 소개: 2026년 · 2027 예산·신규 공고 별도 확인</span>';
// Update authored framing only; official program names and historical evidence remain intact.
for(const root of [fundSection,iitpSection]){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){n.nodeValue=n.nodeValue.replaceAll('휴먼–AI–XR','실감미디어').replaceAll('Human–AI–XR','실감미디어');}}
const oldShowProgram=showProgram;showProgram=function(id){oldShowProgram(id);const detail=$('#fund-detail');detail.innerHTML=detail.innerHTML.replaceAll('휴먼–AI–XR','실감미디어').replaceAll('Human–AI–XR','실감미디어')};
const oldShowIitp=showIitp;showIitp=function(id){oldShowIitp(id);$('#iitp-detail').innerHTML=$('#iitp-detail').innerHTML.replaceAll('휴먼–AI–XR','실감미디어')};
ministries.culture=['문화기술·연구인재·실무교육 · 문체부·KOCCA','콘텐츠 제작·문화서비스·관광·스포츠 등 분야의 연구 문제를 개별 공고와 연결합니다. CT 전문인력 양성과 예비·현업인 교육은 별도 참여 경로로 검토합니다.','대학·기업·현장기관의 기술·권리·검증 역할을 정하고 R&D와 교육 지원의 신청 자격·회계를 구분합니다.',['S37','S38','S29']];
ministries.science=['핵심기술·연구인재 · 과기정통부·IITP','실감콘텐츠·공간 재현·디바이스·감각·상호작용·AI 융합을 폭넓게 검토합니다. 기존 가상융합대학원과의 공동연구를 우선 협의합니다.','기술 기준선·RFP 적합성·연구팀·검증장비를 확보합니다. 2026 소개와 2027 신규 지원을 구분합니다.',['S32','S33']];showMinistry('culture');
$('[data-ministry="science"] small').textContent='실감 핵심기술 · 연구인재';

const originalProposal=document.createElement('details');originalProposal.className='legacy-proposal';originalProposal.innerHTML='<summary>이전 세부 기획안 · 휴먼–AI–XR 중심 사례 및 교육부 앵커 연계</summary><p class="small">아래는 기존의 특정 기획 사례입니다. 현재 후속사업의 전체 범위는 위의 실감미디어 전반 제안을 따릅니다.</p>';
while($('#recommendations').firstChild)originalProposal.append($('#recommendations').firstChild);
$('#future>h2').textContent='실감미디어 미래인재·공동연구 네트워크';
$('#recommendations').innerHTML=`<div class="thesis"><p class="eyebrow">후속사업 제안 · 협약·선정 미확정</p><h3>공유교육을 기반으로,<br>전 생애 역량과 현장 연구를 연결하다.</h3><p>학부·성인·재직자·석박사에게 열린 교육체계와 산업 수요 기반 공동연구를 구축합니다. 실감미디어의 콘텐츠·공간·디바이스·서비스를 포괄하고 AI를 필요한 곳에 융합합니다.</p><a href="#transition">변화 근거·연구 영역 →</a> · <a href="#linkage">부처별 연계사업 →</a></div><div class="grid3"><article class="strategy"><span class="number">01 / LEARNING</span><h3>경력을 만드는 공유교육</h3><p>기초–제작·AI 활용–통합–검증의 역량 체계와 스튜디오 PBL·기업 멘토링을 운영합니다. 성인·재직자 과정은 별도 시간표·기초 진단으로 설계합니다.</p></article><article class="strategy"><span class="number">02 / RESEARCH</span><h3>현장 문제로 묶는 공동연구</h3><p>7개교의 보유기술·연구자·장비를 조사해 소수의 우선 과제부터 기획합니다. 연구 질문·기준선·데이터 권리·실증기관을 먼저 확보합니다.</p></article><article class="strategy"><span class="number">03 / CONTINUITY</span><h3>사업을 넘어 유지되는 기반</h3><p>학점교류·LMS·장비 운영을 학칙과 협약으로 정리합니다. GPU·캡처 장비는 이용률·유지비·기존 시설을 확인한 뒤 공동 활용부터 추진합니다.</p></article></div>
<h2>부처별 역할과 인재양성 연결</h2><div class="table-wrap"><table><thead><tr><th>경로</th><th>제안 역할</th><th>신청·연계 전 확인</th></tr></thead><tbody><tr><td>교육부·지역 앵커</td><td>공동교육·학점·지역 수요·현장 학습</td><td>지역 계획·주관체계·학칙·비용 구분</td></tr><tr><td>문체부·KOCCA</td><td>문화기술 연구·CT 연구인재·예비/현업인 교육</td><td>R&D·교육운영·교육생 참여 경로와 전담기관 구분</td></tr><tr><td>과기정통부·IITP</td><td>실감콘텐츠 핵심기술·공간컴퓨팅·석박사 연구</td><td>RFP·보유기술·대학원 자격·신규/계속 지원</td></tr><tr><td>기업·창업 지원</td><td>기술이전·고객 검증·사업화·경력 형성</td><td>IP·수요계약·법인·투자조건·지속 운영</td></tr></tbody></table></div><p class="small">하나의 컨소시엄이 여러 사업에 자동 선정되는 구조가 아닙니다. 인력·장비·데이터의 사용권과 과제별 업무·회계를 구분합니다. ${sourceLinks(['S25','S37','S38','S32','S33'])}</p>
<h2>2027–2031 실행 로드맵 <small>분석자의 계획 제안</small></h2><div class="roadmap-grid"><article><b>준비 / 착수 후 90일</b><p>학습자·기업 수요, 보유기술·권리, 공유교육 유지 협약, 공고 적합성 조사</p></article><article><b>실증 / 2027–2028</b><p>소규모 공동교과·성인 모듈·산학 연구 시범 운영. 성과 기준선과 추적조사 구축</p></article><article><b>확장 / 2029–2031</b><p>검증된 과정·기술만 확대. 기업 활용·기술이전·재교육·운영비 회수 모델 점검</p></article></div><p class="small">정부 확정 일정·보장된 기술 발전 전망이 아닙니다. 공모 일정, 협약과 시범 결과에 따라 조정합니다.</p>
<details open><summary>성과지표 · 인원과 건수에 활용·경력 지표를 더하기</summary><div class="table-wrap"><table><thead><tr><th>영역</th><th>제안 지표</th><th>분모·증빙</th></tr></thead><tbody><tr><td>교육</td><td>완수·역량 향상·기업 실사용</td><td>참여자/완수자, 사전·사후 동일 기준, 기업 확인서</td></tr><tr><td>초기 경력</td><td>직무 일치·채용 전환·12개월 유지</td><td>추적 대상·응답자 수와 무응답을 별도 공개</td></tr><tr><td>성인·재직자</td><td>6개월 현장 적용·전환·학습 지속</td><td>수료자 코호트와 동의 기반 추적. 임금 변화의 인과효과 단정 금지</td></tr><tr><td>연구</td><td>논문·특허·학위·벤치마크·기술이전</td><td>사업 귀속·중복 제거·학위 수여 증빙·계약</td></tr><tr><td>창업</td><td>유료 고객·매출·3년 생존</td><td>창업 연도별 코호트, 관찰 기간 미도래 구분</td></tr><tr><td>지역·공유</td><td>기업 활용·지역 정착·시설 공동 활용</td><td>동의 기반 조사, 사용 로그·운영비·수요기관 증빙</td></tr></tbody></table></div><p>현재 실적은 <b>향후 입력</b>. 이 지표는 기존 컨소시엄 성과가 부족하거나 측정이 없었다는 단정이 아닙니다.</p></details><p><a href="proposal-renewal.md" download>실감미디어 후속사업 통합 제안서 내려받기 ↗</a> · <a href="document-review.md" download>첨부 문서 검토 메모 ↗</a></p>`;
$('#recommendations').append(originalProposal);
overview.querySelector('.hero>div>p:not(.eyebrow)').innerHTML='공유교육의 성과를 읽고,<br>실감미디어 전반의 연구와 인재양성으로 연결합니다.';
overview.querySelector('.orbit').innerHTML='<div class="portfolio-orbit"><b>실감미디어<small>연구 · 인재양성</small></b><span>콘텐츠·미디어</span><span>공간·시뮬레이션</span><span>디바이스·감각</span><span>서비스·경험</span><span>AI·지능화</span><span>신뢰·표준</span></div>';
overview.querySelector('.orbit').setAttribute('aria-label','실감미디어 전반의 여섯 연구·교육 영역, 분석 제안');
overview.querySelectorAll('.fund-banner').forEach(b=>b.remove());overview.querySelector('.hero').insertAdjacentHTML('afterend','<div class="renew-entry"><a href="#transition"><small>AI·인재전환</small><b>학령인구·산업 변화에 대응하는 교육과 연구 →</b></a><a href="#linkage"><small>부처별 연계</small><b>문체부·KOCCA / 과기정통부·IITP →</b></a></div>');
sections.splice(0,sections.length,['overview','개요'],['explore','성과 탐색'],['compare','대학별 분석'],['trajectory','연구 흐름'],['transition','AI·인재전환'],['linkage','부처별 연계'],['future','후속 제언'],['entry','자료 입력'],['sources','출처']);
$('nav').innerHTML=sections.map(([id,label])=>`<a href="#${id}" data-section="${id}">${label}</a>`).join('');
window.removeEventListener('hashchange',showSection);
let activeRenewalSection=null;
showSection=function(){let raw=location.hash.slice(1),id=['funding','kocca','iitp'].includes(raw)?'linkage':raw;if(!sections.some(s=>s[0]===id))id=location.search?'explore':'overview';sections.forEach(([key])=>{const el=document.getElementById(key);if(el)el.hidden=key!==id});const selected=raw==='iitp'?'iitp':'kocca';fundSection.hidden=selected!=='kocca';iitpSection.hidden=selected!=='iitp';document.querySelectorAll('[data-section]').forEach(a=>{if(a.dataset.section===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.querySelectorAll('.agency-tabs [role=tab]').forEach(a=>{const active=a.id==='tab-'+selected;a.setAttribute('aria-selected',String(active));a.tabIndex=active?0:-1});if(activeRenewalSection!==id){activeRenewalSection=id;window.scrollTo({top:0,behavior:'instant'})}};
window.addEventListener('hashchange',showSection);window.addEventListener('popstate',showSection);
function activateAgency(id){history.pushState(null,'','#'+id);showSection()}
document.querySelectorAll('.agency-tabs a').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();activateAgency(a.id.slice(4))});a.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const id=e.key==='Home'?'kocca':e.key==='End'?'iitp':a.id==='tab-kocca'?'iitp':'kocca';activateAgency(id);document.getElementById('tab-'+id).focus()}})});
overview.querySelector('.stat-strip>div:last-child strong').textContent=SOURCES.length;
$('#bibliography').insertAdjacentHTML('beforeend',RENEWAL_SOURCES.map(s=>`<p><b>${s.id}</b> · <a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><br><span class="small">${s.date} · 확인 ${s.accessed}${s.kind?' · '+s.kind:''}</span></p>`).join(''));showSection();
